use_frameworks!

platform :ios, '10.0'

target 'TestModule_Example' do
  pod 'TestModule', :path => '../'

  target 'TestModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
