source 'https://github.com/Hao-yiwen/ios-study'
source 'https://cdn.cocoapods.org/'

use_frameworks!

platform :ios, '10.0'

target 'TestModule_Example' do
  pod 'TestModule', '~> 0.1.3'

  target 'TestModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end